apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluentd.conf: |
    <source>
      @type tail
      path /var/log/containers/*springboot-container*.log
      pos_file /fluentd/log/fluentd_springboot.pos
      tag springboot.logs
      format json
    </source>

    <source>
      @type tail
      path /var/log/containers/*angular-container*.log
      pos_file /fluentd/log/fluentd_angular.pos
      tag angular.logs
      format json
    </source>

    <match springboot.logs>
      @type file
      path /fluentd/log/springboot_output.log
      append true
    </match>

    <match angular.logs>
      @type file
      path /fluentd/log/angular_output.log
      append true
    </match>
