version: '3.8'
services:
  fluentd:
    image: fluent/fluentd:v1.16-1
    ports:
      - "24224:24224"    # Port Fluentd pour les logs
      - "24224:24224/udp"
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
