apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular-app
          image: angular-app:latest
          ports:
            - containerPort: 80
          env:
            - name: SPRINGBOOT_API_URL
              value: "http://springboot-app:8080"
