- name: Déployer le système d'inventaire
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Installer Node.js via Homebrew
      homebrew:
        name: node
        state: present
      become: false

    - name: Installer npm via Homebrew
      homebrew:
        name: npm
        state: present
      become: false
    - name: Créer le répertoire pour l'application Angular
      file:
        path: /var/www/angular-app
        state: directory
      become: false


    - name: Installer OpenJDK 17 via Homebrew
      homebrew:
        name: openjdk@17
        state: present
      become: false
    - name: Installer MySQL
      homebrew:
        name: mysql
        state: present
      become: false

    - name: Installer phpMyAdmin via Homebrew
      homebrew:
        name: phpmyadmin
        state: present
      become: false
    - name: Redémarrer Apache via Homebrew
      command: brew services restart apache2
      become: false

